# Generated by Django 5.0 on 2024-01-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=254)),
                ('date_time', models.DateTimeField()),
                ('location', models.ManyToManyField(to='contacts.contact')),
            ],
        ),
    ]
